# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PerlIO-via-CBC
version:      0.07
version_from: lib/PerlIO/via/CBC.pm
installdirs:  site
requires:
    Crypt::CBC:                    2.12
    Crypt::DES:                    2.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
